# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmtPayment', models.DateTimeField(auto_created=True)),
                ('out_trade_no', models.CharField(max_length=64)),
                ('receiptAmount', models.IntegerField()),
                ('user', models.IntegerField(max_length=16)),
            ],
        ),
    ]
