# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_auto_20170519_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='rewardTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6253\u8d4f\u65e5\u671f'),
        ),
    ]
