# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-07 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20170517_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentEssence',
            field=models.BooleanField(default=False, verbose_name='\u4e66\u7c4d\u7cbe\u534e'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentStick',
            field=models.BooleanField(default=False, verbose_name='\u4e66\u7c4d\u7f6e\u9876'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='isShow',
            field=models.BooleanField(default=False, verbose_name='\u8bc4\u8bba\u662f\u5426\u663e\u793a'),
        ),
    ]
